import { t } from "@util/translate";

export const gallery = {
  label: "Galería",
  name: "gallery",
  icon: "portfolio",
  folder: "src/content/gallery",
  create: true,
  delete: true,
  slug: "{{slug}}",
  extension: "mdx",
  format: "frontmatter",
  identifier_field: "title",
  sortable_fields: {
    fields: ["title", "date", "location"],
    default: {
      field: "date",
      direction: "Descending",
    },
  },
  fields: [
    {
      label: "Título",
      name: "title",
      widget: "string",
      required: true,
      hint: "Título de la foto o video",
    },
    {
      label: "Fecha",
      name: "date",
      widget: "datetime",
      required: true,
      date_format: "dd-MM-yyyy",
      time_format: false,
    },
    {
      label: "Lugar",
      name: "location",
      widget: "string",
      required: false,
      hint: "Ej: Auditorio Municipal, Teatro Principal, etc.",
    },
    {
      label: "Tipo de medio",
      name: "media_type",
      widget: "select",
      options: ["photo", "video"],
      default: "photo",
      required: true,
    },
    {
      label: "Imagen/Foto",
      name: "thumbnail",
      widget: "image",
      required: false,
      hint: "Sube la foto o imagen de portada (para videos será la miniatura)",
    },
    {
      label: "URL de YouTube",
      name: "video_url",
      widget: "string",
      required: false,
      hint: "Solo para videos: URL completa de YouTube",
    },
    {
      label: "Descripción",
      name: "description",
      widget: "text",
      required: false,
      hint: "Descripción opcional del momento",
    },
    {
      label: "Destacado",
      name: "featured",
      widget: "boolean",
      default: false,
      required: false,
      hint: "Marcar para destacar en la galería",
    },
  ],
};
