import { t } from "@util/translate";

export const gallery = {
  label: "Galería",
  name: "gallery",
  icon: "portfolio",
  folder: "src/content/gallery",
  create: true,
  delete: true,
  slug: "{{slug}}",
  extension: "mdx",
  format: "frontmatter",
  identifier_field: "title",
  fields: [
    {
      label: "Nombre del concierto/evento",
      name: "title",
      widget: "string",
      required: true,
    },
    {
      label: "Fecha del concierto",
      name: "date",
      widget: "datetime",
      required: true,
      date_format: "dd-MM-yyyy",
      time_format: false,
    },
    {
      label: "Descripción del evento",
      name: "description",
      widget: "text",
      required: false,
      hint: "Breve descripción del concierto o evento",
    },
    {
      label: "Imagen principal",
      name: "thumbnail",
      widget: "image",
      required: false,
      hint: "Imagen de portada del concierto (opcional)",
    },
    {
      label: "Lugar",
      name: "location",
      widget: "string",
      required: false,
      hint: "Ej: Auditorio Municipal, Teatro Principal, etc.",
    },
    {
      label: "Tipo de evento",
      name: "event_type",
      widget: "select",
      options: ["Concierto", "Gala benéfica", "Ensayo", "Evento especial", "Colaboración"],
      required: false,
    },
    {
      label: "Destacado",
      name: "featured",
      widget: "boolean",
      default: false,
      required: false,
      hint: "Marcar si quieres que aparezca destacado en la galería",
    },
    {
      label: "Videos del concierto",
      name: "videos",
      widget: "list",
      required: true,
      min: 1,
      summary: "{{fields.title}}",
      fields: [
        {
          label: "Título del video",
          name: "title",
          widget: "string",
          required: true,
          hint: "Ej: Noche de Paz, Hallelujah, Ave María",
        },
        {
          label: "URL de YouTube",
          name: "video_url",
          widget: "string",
          required: true,
          hint: "URL completa: https://www.youtube.com/watch?v=xxxxx",
        },
        {
          label: "Descripción del video",
          name: "description",
          widget: "string",
          required: false,
        },
      ],
    },
  ],
};
